description: |-
  Default property that provides detailed product data. Called on the default `templates/pages/product.html` and `templates/pages/amp/product.html` templates, and on several partials in the `templates/components/` subdirectory:

  `account/returns-list.html`,
  `cart/item-options.html`,
  `products/add-to-cart.html`,
  `products/event-date.html`,
  `products/modals/writeReview.html`,
  `products/price.html`,
  `products/product-view.html`,
  `amp/products/product-options.html`,
  `amp/products/product-view.html`, and
  `amp/products/product-view-details.html`.

  **Handlebars Expression** {{product}}
type: object
properties:
  AddThisServiceButtonMeta:
    type: string
  add_this:
    type: array
    items:
      type: object
      properties:
        annotation:
          type: string
        service:
          type: string
  add_to_wishlist_url:
    description: URL to add the product to the customer’s wishlist
    type: string
  availability:
    type: string
  bulk_discount_rates:
    description: List of discount rates for the current product
    type: array
    items:
      type: object
  can_purchase:
    description: Boolean that indicates whether the product is available for purchase
    type: boolean
  cart_url:
    description: URL to the customer’s shopping cart
    type: string
  category:
    type: array
    items:
      type: string
  customizations:
    description: 'Product customizations (for example, a T-shirt size); these correspond to configurable fields and numeric-text product options in the BigCommerce control panel'
    type: array
    items:
      type: object
  description:
    description: (HTML) description of the product
    type: string
  detail_messages:
    description: Status messages for display at the top of the product page
    type: string
  gift_wrapping_available:
    description: Whether or not gift wrapping is enabled
    type: boolean
  id:
    description: Unique ID for the product
    type: string
  images:
    description: 'List of all images for this product, in Stencil image format (as configured in config.json; used with the getImage Handlebars helper)'
    type: array
    items:
      type: object
      properties:
        alt:
          type: string
        data:
          type: string
  main_image:
    description: Primary image to display when the product details page loads
    type: object
    properties:
      alt:
        type: string
      data:
        type: string
  max_purchase_quantity:
    description: Maximum quantity that can be purchased at once
    type: integer
  meta_description:
    type: string
  meta_keywords:
    description: 'Optional search keywords that merchants may enter in the control panel’s "Add a Product" or “Edit a Product” page, to characterize the product in meta tags and storefront searches'
    type: string
  min_purchase_quantity:
    description: Minimum quantity that can be purchased at once
    type: integer
  num_reviews:
    description: Number of reviews the product has
    type: integer
  options:
    type: array
    items:
      type: object
  page_title:
    type: string
  price:
    $ref: ../product/price.yml
  rating:
    description: Rating for the product
    type: integer
  related_products:
    $ref: ../product/related_products.yml
  reviews:
    $ref: ../product/reviews.yml
  shipping_messages:
    type: array
    items:
      type: object
  show_quantity_input:
    type: integer
  sku:
    description: Default product variant when no options are selected
    type: string
  tags:
    description: Keywords by which this product can also be identified
    type: array
    items:
      type: object
  title:
    description: Displayed name of the product
    type: string
  upc:
    description: Optional UPC code for the product
    type: 'null'
  url:
    description: URL to the product detail page
    type: string
  videos:
    $ref: ../product/videos.yml
  warranty:
    description: Optional warranty text set by the merchant
    type: string
  custom_fields:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
          example: 61
        name:
          type: string
          example: unavailable_for
        value:
          type: string
          example: CAD
