openapi: 3.0.3
info:
  version: '3'
  title: Carts Settings
  description: Manage settings related to carts.
  termsOfService: 'http://www.bigcommerce.com/terms'
  contact:
    name: BigCommerce
    url: 'https://www.bigcommerce.com'
    email: support@bigcommerce.com
servers:
  - url: 'https://api.bigcommerce.com/stores/{store_hash}/v3'
    variables:
      store_id:
        default: unknown
tags:
  - name: Carts Settings
paths:
  /carts/settings:
    get:
      summary: Get Global Cart Settings
      description: Returns the global cart settings of a store.
      tags:
        - Carts Settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalCartSettingsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update Global Cart Settings
      description: Update the global cart settings of a store.
      tags:
        - Carts Settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalCartSettingsRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalCartSettingsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/carts/settings/channels/{channel_id}':
    get:
      summary: Get Channel Cart Settings
      description: Returns the per-channel overrides for the cart settings of a store.
      tags:
        - Carts Settings
      parameters:
        - name: channel_id
          description: The channel ID of the settings overrides
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelCartSettingsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update Channel Cart Settings
      description: Update the per-channel overrides for the cart settings of a store
      tags:
        - Carts Settings
      parameters:
        - name: channel_id
          description: The channel ID of the settings overrides
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelCartSettingsRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelCartSettingsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessible entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CartSettings:
      description: Represents all settings related to the shopping cart functionality of a store
      type: object
      properties:
        allow_purchasing:
          type: boolean
      x-tags:
        - Models
    ChannelCartSettings:
      description: Represents all settings overrides related to the shopping cart functionality of a store for a channel
      type: object
      properties:
        allow_purchasing:
          type: boolean
          nullable: true
      x-tags:
        - Models
    ChannelCartSettingsRequest:
      allOf:
        - $ref: '#/components/schemas/ChannelCartSettings'
        - description: The request object for updating the cart settings overrides of a store for a channel
      x-tags:
        - Models
    ChannelCartSettingsResponse:
      description: The response object of cart settings overrides for a channel
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ChannelCartSettings'
        meta:
          type: object
      x-tags:
        - Models
    GlobalCartSettingsRequest:
      allOf:
        - $ref: '#/components/schemas/CartSettings'
        - description: The request object for updating the cart settings of a store at the global level
          required:
            - allow_purchasing
      x-tags:
        - Models
    GlobalCartSettingsResponse:
      description: The response object of cart settings at the global level
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CartSettings'
        meta:
          type: object
      x-tags:
        - Models
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        title:
          type: string
        type:
          type: string
        instance:
          type: string
        errors:
          type: object
      x-tags:
        - Models
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
