info:
  version: 3.0.0
  title: Order Settings
  termsOfService: 'http://www.bigcommerce.com/terms'
  description: Manage order settings of BigCommerce stores.
  contact:
    name: BigCommerce
    url: 'https://www.bigcommerce.com'
    email: support@bigcommerce.com
paths:
  /orders/settings:
    get:
      summary: Get Global Order Settings
      description: Returns global order settings.
      tags:
        - Order Settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/GlobalOrderSettings'
                  meta:
                    type: object
        '400':
          description: Bad request. Authentication Required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
    put:
      summary: Update Global Order Settings
      description: Updates global order settings.
      tags:
        - Order Settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalOrderSettings'
            examples:
              EnableMultipleOrderNotifications:
                $ref: '#/components/examples/EnableMultipleOrderNotifications'
              DisableOrderPlacedNotificatons:
                $ref: '#/components/examples/GlobalOrderSettingsDisableOrderPlacedNotificatons'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/GlobalOrderSettings'
                  meta:
                    type: object
        '400':
          description: Bad request. Authentication Required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '422':
          description: 'Order settings data is not valid. This is the result of missing required fields, or of invalid data. See the response for more details.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse422'
  '/orders/settings/channels/{channel_id}':
    get:
      summary: Get Channel Order Settings
      description: Returns order settings for a specific channel.
      tags:
        - Order Settings
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: path
          name: channel_id
          required: true
          description: Channel Id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ChannelOrderSettings'
                  meta:
                    type: object
        '400':
          description: Bad request. Authentication Required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
    put:
      summary: Update Channel Order Settings
      description: |-
        Updates order settings for a specific channel. 

         **Note:** You must override both notifications `email_addresses` or neither, i.e. either both notification `email_addresses` are an array of valid email addresses, or both `email_addresses` must be null. You may not have one set to an array of addesses and the other set to `null`.
      tags:
        - Order Settings
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: path
          name: channel_id
          required: true
          description: Channel Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelOrderSettings'
            examples:
              OverrideOrderPlacedEmailAddressesAndDisableForwardEmailAddresses:
                $ref: '#/components/examples/ChannelOrderSettingsOverrideOrderPlacedEmailAddressesAndDisableForwardEmail'
              ResetChannelSettings:
                $ref: '#/components/examples/ChannelOrderSettingsReset'
              DisableMultipleNotificatonsForChannels:
                $ref: '#/components/examples/ChannelOrderSettingsDisableBothNotifications'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ChannelOrderSettings'
                  meta:
                    type: object
        '400':
          description: Bad request. Authentication Required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '422':
          description: 'Order settings data is not valid. This is the result of missing required fields, or of invalid data. See the response for more details.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse422'
components:
  schemas:
    GlobalOrderSettings:
      type: object
      properties:
        notifications:
          type: object
          description: Global notification settings.
          properties:
            order_placed:
              description: Global order notification settings.
              type: object
              properties:
                email_addresses:
                  description: Email addresses order notifications will be sent to. Empty array disables order notifications. Not nullable.
                  type: array
                  items:
                    type: string
            forward_invoice:
              description: Global order invoice forward settings.
              type: object
              properties:
                email_addresses:
                  description: Email addresses order invoices will be forwarded to. Empty array disables forwarding order invoices. Not nullable.
                  type: array
                  items:
                    type: string
      example:
        $ref: '#/components/examples/EnableMultipleOrderNotifications/value'
      x-tags:
        - Models
    ChannelOrderSettings:
      type: object
      example:
        $ref: '#/components/examples/EnableMultipleOrderNotifications/value'
      properties:
        notifications:
          type: object
          description: Channel notification settings.
          properties:
            order_placed:
              description: Channel order notification settings.
              type: object
              properties:
                email_addresses:
                  description: Email addresses channel order notifications will be sent to. If null will fall back to global value. Empty array disables order notifications for channel.
                  type: array
                  nullable: true
                  items:
                    type: string
            forward_invoice:
              description: Channel order invoice forward settings.
              type: object
              properties:
                email_addresses:
                  description: Email addresses channel order invoices will be forwarded to. If null will fall back to global value. Empty array disables forwarding order invoices for channel.
                  type: array
                  nullable: true
                  items:
                    type: string
      x-tags:
        - Models
    ErrorResponse400:
      type: object
      properties:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
      x-tags:
        - Models
    ErrorResponse404:
      type: object
      properties:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
      x-tags:
        - Models
    ErrorResponse422:
      type: object
      properties:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
      x-tags:
        - Models
    ErrorResponse:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            errors:
              type: object
      x-tags:
        - Models
    BaseError:
      type: object
      description: |
        Error payload for the BigCommerce API.
      properties:
        status:
          description: |
            The HTTP status code.
          type: integer
        title:
          description: |
            The error title describing the particular error.
          type: string
        type:
          type: string
      x-tags:
        - Models
    DetailedErrors:
      type: object
      x-tags:
        - Models
  examples:
    EnableMultipleOrderNotifications:
      summary: Enable order placed and forward invoice notifications
      value:
        notifications:
          order_placed:
            email_addresses:
              - admin@mystore.com
              - another-email@mystore.com
          forward_invoice:
            email_addresses:
              - admin@mystore.com
              - another-email@mystore.com
    GlobalOrderSettingsDisableOrderPlacedNotificatons:
      summary: Disable order placed notifications at global level
      value:
        notifications:
          order_placed:
            email_addresses: []
    ChannelOrderSettingsOverrideOrderPlacedEmailAddressesAndDisableForwardEmail:
      summary: Override order placed email addresses and forward email addresses global value for channel
      value:
        notifications:
          order_placed:
            email_addresses:
              - admin@mystore.com
              - another-email@mystore.com
          forward_invoice:
            email_addresses: []
    ChannelOrderSettingsReset:
      summary: Reset order placed email addresses to global value for channel
      value:
        notifications:
          order_placed:
            email_addresses: null
          forward_invoice:
            email_addresses: null
    ChannelOrderSettingsDisableBothNotifications:
      summary: Disable order placed notifications for channel
      value:
        notifications:
          order_placed:
            email_addresses: []
          forward_invoice:
            email_addresses: []
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
servers:
  - url: 'https://api.bigcommerce.com/stores/{store_hash}/v3'
    description: Production API Gateway
    variables:
      store_hash:
        default: abc123
        description: Store hash used to identify the store.
openapi: 3.0.1
