openapi: 3.0.1
info:
  title: Pickup
  version: '3.0'
  termsOfService: 'https://www.bigcommerce.com/terms'
servers:
  - url: 'https://api.bigcommerce.com'
    variables:
      store_hash:
        default: store_hash
paths:
  '/stores/{store_hash}/v3/pickup/methods':
    get:
      tags:
        - Pickup Methods
      summary: Get Pickup Methods
      description: |-
        
        Retrieves a list of Pickup Methods.
        
        ## Examples

        This list can be filtered to return pickup method objects specific to a list of requested pickup method IDs. This is achieved by appending the query string **?id:in=1,3,5** to the resource **/pickup/methods**.

        ```http
        GET /pickup/methods?id:in=1,3,5
        ```
      parameters:
        - name: id:in
          description: Comma separated list of pickup method IDs.
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has been processed and a list of Pickup Methods has been returned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PickupMethod'
                  meta:
                    $ref: '#/components/schemas/MetaCollection'
    post:
      tags:
        - Pickup Methods
      description: |-
        Creates one or many pickup methods.
        
        This is a batch operation that can create up to 10 pickup methods objects can be done in one request.
        
        ## Limits
        * Limit of updating 10 pickup method objects per `POST` request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PostRequestPickupMethod'
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has been successfully processed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PickupMethod'
                  meta:
                    type: object
    put:
      tags:
        - Pickup Methods
      description: |-
        Update existing pickup methods.
        
        This is a batch operation that can update 10 pickup methods objects in one request.
        
        Only the `id` property of the pickup method object is required as part of the request. Pickup method property that are not provided will maintain their existing values.
        
        ## Limits
        * Limit of updating 10 pickup method objects per `PUT` request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PutRequestPickupMethod'
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has been successfully processed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PickupMethod'
                  meta:
                    type: object
    delete:
      tags:
        - Pickup Methods
      description: Delete existing pickup methods.
      parameters:
        - name: id:in
          description: Comma separated list of pickup method IDs.
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Request has been successfully processed.
      summary: Delete Pickup Methods
components:
  schemas:
    BasePickupMethod:
      type: object
      properties:
        location_id:
          type: integer
          example: 2
        display_name:
          type: string
          minLength: 0
          maxLength: 250
          example: Office Pickup!
        collection_instructions:
          type: string
          minLength: 0
          maxLength: 250
          example: Bring your ID!
        collection_time_description:
          type: string
          minLength: 0
          maxLength: 250
          example: Collect during our opening hours of 0900 - 1700
    PickupMethod:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              example: 1
        - $ref: '#/components/schemas/BasePickupMethod'
    PutRequestPickupMethod:
      allOf:
        - $ref: '#/components/schemas/PickupMethod'
        - required:
            - id
    PostRequestPickupMethod:
      allOf:
        - $ref: '#/components/schemas/BasePickupMethod'
        - required:
            - location_id
            - display_name
            - collection_instructions
            - collection_time_description
    MetaCollection:
      type: object
      properties:
        pagination:
          type: object
          properties:
            offset:
              type: integer
              description: Integer indicates the number of pickup methods between the offset integer and the beginning of the pickup methods list.
              example: 0
            limit:
              type: integer
              description: The maximum number of pickup method objects to return.
              example: 100
            total_items:
              type: integer
              description: Count of all the pickup methods returned.
              example: 4
  securitySchemes:
    X-Auth-Client:
      name: X-Auth-Client
      type: apiKey
      in: header
    X-Auth-Token:
      name: X-Auth-Token
      type: apiKey
      in: header
tags:
  - name: Pickup
    description: BigCommerce Pickup API Definition.
