openapi: 3.0.3
info:
  version: ''
  title: Store Information
  description: 'Get Store Information endpoint, manage store profile settings.'
security:
  - X-Auth-Client: []
  - X-Auth-Token: []
tags:
  - name: Store Information
  - name: Time Zone
paths:
  '/stores/{store_hash}/v2/store':
    get:
      description: Returns metadata about a store.
      summary: Get Store Information
      tags:
        - Store Information
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/StoreInformation'
          examples:
            application/json:
              id: abc123
              domain: my-awesome.store
              secure_url: 'https://my-awesome.stor'
              control_panel_base_url: 'https://store-{store_hash}.mybigcommerce.com'
              status: live
              name: BigCommerce
              first_name: Jane
              last_name: Doe
              address: BigCommerce
              country: United States
              country_code: US
              phone: ''
              admin_email: jane.does@example.com
              order_email: info@janedoes.mybigcommerce.com
              favicon_url: >-
                https://cdn8.bigcommerce.com/r-8816ba2f48b0bcf4bec0c1a954c00e0fc36b/img/bc_favicon.ico
              timezone:
                name: America/Chicago
                raw_offset: -21600
                dst_offset: -18000
                dst_correction: true
                date_format:
                  display: M jS Y
                  export: M jS Y
                  extended_display: 'M jS Y @ g:i A'
              language: en
              currency: USD
              currency_symbol: $
              decimal_separator: .
              thousands_separator: ','
              decimal_places: 2
              currency_symbol_location: left
              weight_units: Ounces
              dimension_units: Inches
              dimension_decimal_places: 2
              dimension_decimal_token: .
              dimension_thousands_token: ','
              plan_name: Standard
              plan_level: Standard
              industry: ''
              logo:
                url: >-
                  https://cdn8.bigcommerce.com/s-{store_hash}/product_images/screen_shot_2018-05-15_at_12.22.26_pm__05547_1529512135.png
              is_price_entered_with_tax: false
              active_comparison_modules: []
              features:
                stencil_enabled: true
                sitewidehttps_enabled: false
                facebook_catalog_id: ''
                checkout_type: optimized
            Response Schema:
              id: nostrud pariatur incididunt
              domain: consequat ut amet
              secure_URL: consectetur ullamco ut Excepteur
              name: id qui cupidatat anim tempor
              first_name: ut dolore elit
              last_name: cupidatat minim
              address: tempor
              country: ex cupidatat
              phone: aliquip dolore pariatur
              admin_email: dolor commodo elit do
              order_email: ea qui
              timezone:
                name: culpa quis sint eiusmod ut
                raw_offset: -25825722
                dst_offset: -97926378
                dst_correction: false
                date_format:
                  display: cupidatat
                  export: est
                  extended_display: cillum qui esse aliquip culpa
              language: nulla commodo incididunt dolor ipsum
              currency: amet in
              currency_symbol: cupidatat deserunt est pariatur
              decimal_separator: in consectetur nisi officia
              thousands_separator: ea irure occaecat qui
              decimal_places: {}
              currency_symbol_location: est cupidatat
              weight_units: minim adipisicing do
              dimension_units: deserunt
              dimension_decimal_places: 50514826
              dimension_decimal_token: deserunt est aliqua Duis
              'dimension_thousands_token:': sint voluptate esse tempor
              plan_name: Ut
              plan_level: pariatur ullamco veniam ad
              industry: pariatur culpa est
              logo:
                url: aliquip in aliqua consectetur ullamco
              is_price_entered_with_tax: false
              features:
                stencil_enabled: true
                sitewidehttps_enabled: anim occaecat exercitation conse
                facebook_catalog_id: aliquip sed adipisicing quis
                checkout_type: qui mollit id aliqua ut
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      produces:
        - Time
    parameters:
      - type: string
        name: store_hash
        in: path
        required: true
  '/stores/{store_hash}/v2/time':
    get:
      description: >-
        Returns the system timestamp at the time of the request. The time
        resource is useful for validating API authentication details and testing
        client connections.
      summary: Get System Timestamp
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/timeStamp_Full'
          examples:
            application/json:
              time: 1529512970
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - Time Zone
    parameters:
      - type: string
        name: store_hash
        in: path
        required: true
  /store:
    get:
      description: Returns metadata about a store.
      summary: Get Store Information
      tags:
        - Store Information
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/StoreInformation'
          examples:
            application/json:
              id: abc123
              domain: my-awesome.store
              secure_url: 'https://my-awesome.stor'
              control_panel_base_url: 'https://store-{store_hash}.mybigcommerce.com'
              status: live
              name: BigCommerce
              first_name: Jane
              last_name: Doe
              address: BigCommerce
              country: United States
              country_code: US
              phone: ''
              admin_email: jane.does@example.com
              order_email: info@janedoes.mybigcommerce.com
              favicon_url: >-
                https://cdn8.bigcommerce.com/r-8816ba2f48b0bcf4bec0c1a954c00e0fc36b/img/bc_favicon.ico
              timezone:
                name: America/Chicago
                raw_offset: -21600
                dst_offset: -18000
                dst_correction: true
                date_format:
                  display: M jS Y
                  export: M jS Y
                  extended_display: 'M jS Y @ g:i A'
              language: en
              currency: USD
              currency_symbol: $
              decimal_separator: .
              thousands_separator: ','
              decimal_places: 2
              currency_symbol_location: left
              weight_units: Ounces
              dimension_units: Inches
              dimension_decimal_places: 2
              dimension_decimal_token: .
              dimension_thousands_token: ','
              plan_name: Standard
              plan_level: Standard
              industry: ''
              logo:
                url: >-
                  https://cdn8.bigcommerce.com/s-{store_hash}/product_images/screen_shot_2018-05-15_at_12.22.26_pm__05547_1529512135.png
              is_price_entered_with_tax: false
              active_comparison_modules: []
              features:
                stencil_enabled: true
                sitewidehttps_enabled: false
                facebook_catalog_id: ''
                checkout_type: optimized
            Response Schema:
              id: nostrud pariatur incididunt
              domain: consequat ut amet
              secure_URL: consectetur ullamco ut Excepteur
              name: id qui cupidatat anim tempor
              first_name: ut dolore elit
              last_name: cupidatat minim
              address: tempor
              country: ex cupidatat
              phone: aliquip dolore pariatur
              admin_email: dolor commodo elit do
              order_email: ea qui
              timezone:
                name: culpa quis sint eiusmod ut
                raw_offset: -25825722
                dst_offset: -97926378
                dst_correction: false
                date_format:
                  display: cupidatat
                  export: est
                  extended_display: cillum qui esse aliquip culpa
              language: nulla commodo incididunt dolor ipsum
              currency: amet in
              currency_symbol: cupidatat deserunt est pariatur
              decimal_separator: in consectetur nisi officia
              thousands_separator: ea irure occaecat qui
              decimal_places: {}
              currency_symbol_location: est cupidatat
              weight_units: minim adipisicing do
              dimension_units: deserunt
              dimension_decimal_places: 50514826
              dimension_decimal_token: deserunt est aliqua Duis
              'dimension_thousands_token:': sint voluptate esse tempor
              plan_name: Ut
              plan_level: pariatur ullamco veniam ad
              industry: pariatur culpa est
              logo:
                url: aliquip in aliqua consectetur ullamco
              is_price_entered_with_tax: false
              features:
                stencil_enabled: true
                sitewidehttps_enabled: anim occaecat exercitation conse
                facebook_catalog_id: aliquip sed adipisicing quis
                checkout_type: qui mollit id aliqua ut
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      produces:
        - Time
  /time:
    get:
      description: >-
        Returns the system timestamp at the time of the request. The time
        resource is useful for validating API authentication details and testing
        client connections.
      summary: Get System Timestamp
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/timeStamp_Full'
          examples:
            application/json:
              time: 1529512970
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - Time Zone
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
